---
#L'ensemble de variables rÃ©quis dans le main.yml du dossier tasks
pdns_master_ip: 172.5.0.20
pdns_slave_ip: 172.5.0.21
dns_local_suffix: uauben
wipe: false
c_state: '{{ "absent" if wipe | bool else "started" }}'
i_state: present
alpine: false
node_user: abdoul
